updates for caom2-2.3.5 changes
opencadc/caom2service pull request #21
Opened 2017-09-06 23:00 UTC by pdowler

2017-09-07 18:25 UTC, pdowler commented
ivoa support views moved to caom2db

2017-09-11 17:06 UTC, andamian requested changes

2017-09-11 17:06 UTC, andamian commented on caom2-tap/build.gradle
> +    compile 'org.opencadc:caom2:[2.3.4,30)'
Missing "." in 3.0

2017-09-11 17:15 UTC, pdowler commented on caom2-tap/build.gradle
> +    compile 'org.opencadc:caom2:[2.3.4,30)'
lol

2017-09-11 18:09 UTC, andamian approved these changes

2017-09-11 18:10 UTC, merged