Added integration tests for cutout generators
opencadc/caom2service pull request #29
Opened 2017-10-27 18:13 UTC by andamian

2017-10-27 18:45 UTC, jburke-cadc approved these changes

2017-10-27 18:46 UTC, jburke-cadc approved these changes

2017-10-27 20:11 UTC, pdowler requested changes
Both tests need a test with invalid input in order to verify that the target web service validates and fails with a 400 response.

I am not certain that an http HEAD is sufficient for both valid and invalid but an invalid input test would also check that assumption.

2017-10-28 02:49 UTC, pdowler approved these changes

2017-10-28 02:49 UTC, merged